version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: llmteachme-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: llmteachme
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - llmteachme-network

networks:
  llmteachme-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
